### ISSUE TITLE
v1.0.2 has breaking changes

### ISSUE THREAD

**Issue by JPeer264** [Connormiha/decimal-to-any#1]
I just updated to `v1.0.2` and realized that in `index.js@convertorInteger` the last parameter changed to `{ alphabet }`. Object destruction is not supported in Node v<6.

As in your `package.json` `engines` is set to v4.2.0 I guess this might be a breaking change instead of an patch release.

**Comment by Connormiha** [comment]
Yes you right. I have already removed destructing for Node 4. Thanks.
